// ui/student/src/components/HomePage.tsx
import type { ReactElement } from "react"
import { CircleAlert, CircleCheck } from "lucide-react"
import type { Category, Grade, StudentInfo } from "@common/types"
import { Badge } from "@/components/ui/badge"
import { Progress } from "@/components/ui/progress"
import { Separator } from "@/components/ui/separator"
import {
	Table,
	TableBody,
	TableCell,
	TableHead,
	TableHeader,
	TableRow,
} from "@/components/ui/table"

interface Props {
	user: StudentInfo | null
	grade: Grade | null
	categories: Category[]
}

function Section({
	title,
	action,
	children,
}: {
	title: string
	action?: ReactElement
	children: React.ReactNode
}): ReactElement {
	return (
		<section className="rounded-lg border bg-card p-6">
			<div className="mb-5 flex items-center justify-between gap-3">
				<h2 className="text-lg font-semibold">{title}</h2>
				{action}
			</div>
			{children}
		</section>
	)
}

// A ratio as a labelled bar. Easier to read than a sentence, and the
// figure is still printed beside it for anyone who wants it exactly.
function Meter({
	label,
	value,
	of,
}: {
	label: string
	value: number
	of: number
}): ReactElement {
	return (
		<div className="flex flex-col gap-2">
			<div className="flex items-baseline justify-between gap-3 text-sm">
				<span className="text-muted-foreground">{label}</span>
				<span className="font-medium tabular-nums">
					{value} / {of}
				</span>
			</div>
			<Progress
				value={of === 0 ? 0 : Math.min(100, (value / of) * 100)}
			/>
		</div>
	)
}

function greeting(hour: number): string {
	if (hour < 12) {
		return "Good morning"
	}
	if (hour < 18) {
		return "Good afternoon"
	}
	return "Good evening"
}

// The landing view: where the student stands, and the requirements they
// are judged against. Every number here is read from the server, not
// derived in the browser: budget spent, categories spanned, and each
// requirement with whether it is met all come from
// /student/api/user_info. The rules have one definition, and this is a
// view of it.
export function HomePage({ user, grade, categories }: Props): ReactElement {
	// Requirements name category ids; the labels come from the
	// categories list, which is the consumer's job to map.
	const categoryName = new Map(
		categories.map((c): [string, string] => [c.id, c.name]),
	)

	function requirementLabel(id: number): string {
		const requirement = grade?.requirements.find(
			(r): boolean => r.id === id,
		)
		if (requirement === undefined) {
			return ""
		}
		return requirement.category_ids
			.map((c): string => categoryName.get(c) ?? c)
			.join(" / ")
	}

	const allMet =
		user !== null &&
		user.requirements.every((r): boolean => r.met) &&
		user.distinct_categories_used >= user.min_distinct_categories

	const showsVerdict =
		user !== null &&
		(user.requirements.length > 0 || user.min_distinct_categories > 0)

	// The first name only. The header already carries the full name, and
	// a second copy of it on the page is one more thing to read past —
	// a greeting is meant to be glanced at.
	const firstName =
		user === null ? "" : (user.name.split(" ")[0] ?? user.name)

	return (
		<div className="flex flex-col gap-6">
			{user !== null && (
				<p className="text-2xl">
					{greeting(new Date().getHours())}, {firstName}
				</p>
			)}

			<div className="grid gap-6 lg:grid-cols-2">
				{grade !== null && (
					<Section
						title="Status"
						/*
						Openness is the server's answer, derived from the
						window's two bounds. Nothing here recomputes it from
						the clock: the page and the write functions must
						agree, or a student is offered a button that cannot
						work.
					*/
						action={
							<Badge
								variant={
									grade.is_open ? "default" : "secondary"
								}
							>
								{grade.is_open ? "Open" : "Closed"}
							</Badge>
						}
					>
						<div className="flex flex-col gap-5">
							<p className="text-sm text-muted-foreground">
								{grade.is_open ? (
									<>
										Enrollment is open for your grade.
										{grade.closes_at !== null &&
											` It closes on ${new Date(
												grade.closes_at,
											).toLocaleString()}.`}
									</>
								) : (
									<>
										Enrollment is closed for your grade. You
										may not make any changes.
										{grade.opens_at !== null &&
											new Date(grade.opens_at) >
												new Date() &&
											` It opens on ${new Date(
												grade.opens_at,
											).toLocaleString()}.`}
									</>
								)}
							</p>

							{showsVerdict && (
								<>
									<Separator />
									<p
										className={
											allMet
												? "flex items-center gap-2 text-sm"
												: "flex items-center gap-2 text-sm text-destructive"
										}
									>
										{allMet ? (
											<CircleCheck
												className="size-4 shrink-0 text-primary"
												aria-hidden="true"
											/>
										) : (
											<CircleAlert
												className="size-4 shrink-0"
												aria-hidden="true"
											/>
										)}
										{allMet
											? "You have satisfied your requirements."
											: "You have not satisfied your requirements."}
									</p>
								</>
							)}
						</div>
					</Section>
				)}

				{user !== null && (
					<Section title="Available Selections">
						<div className="flex flex-col gap-5">
							{/*
							What is left, not what is spent. "Periods used"
							made a student subtract to answer the only
							question they were asking — how many more can I
							take — so the bar and the figure both count down.
						*/}
							{user.max_budgeted_periods === null ? (
								<p className="text-sm text-muted-foreground">
									You may take as many courses as you like.
									You currently hold{" "}
									<strong>
										{user.budgeted_periods_used}
									</strong>
									.
								</p>
							) : (
								<Meter
									label="Selections remaining"
									value={Math.max(
										0,
										user.max_budgeted_periods -
											user.budgeted_periods_used,
									)}
									of={user.max_budgeted_periods}
								/>
							)}

							{user.min_distinct_categories > 0 && (
								<Meter
									label="Categories spanned"
									value={user.distinct_categories_used}
									of={user.min_distinct_categories}
								/>
							)}
						</div>
					</Section>
				)}
			</div>

			{user !== null && user.requirements.length > 0 && (
				<Section title="Requirements">
					<div className="overflow-x-auto rounded-lg border">
						<Table>
							<TableHeader>
								<TableRow>
									<TableHead scope="col" rowSpan={2}>
										Categories
									</TableHead>
									<TableHead scope="colgroup" colSpan={2}>
										Periods
									</TableHead>
									<TableHead scope="col" rowSpan={2}>
										Status
									</TableHead>
								</TableRow>
								<TableRow>
									<TableHead scope="col">Enrolled</TableHead>
									<TableHead scope="col">Required</TableHead>
								</TableRow>
							</TableHeader>
							<TableBody>
								{user.requirements.map((req): ReactElement => (
									<TableRow key={req.id}>
										<TableHead scope="row">
											{requirementLabel(req.id)}
										</TableHead>
										<TableCell className="tabular-nums">
											{req.satisfied_periods}
										</TableCell>
										<TableCell className="tabular-nums">
											{req.min_period_count}
										</TableCell>
										<TableCell>
											<Badge
												variant={
													req.met
														? "default"
														: "secondary"
												}
											>
												{req.met ? "OK" : "Unsatisfied"}
											</Badge>
										</TableCell>
									</TableRow>
								))}
							</TableBody>
						</Table>
					</div>
				</Section>
			)}
		</div>
	)
}

// ui/student/src/lib/HomePage.svelte
<script lang="ts">
	// The landing view: identity, requirements, and the timetable.
	// Every number here is read from the server, not derived in the
	// browser: budget spent, categories spanned, and each requirement
	// with whether it is met all come from /student/api/user_info. The
	// rules have one definition, and this is a view of it.
	import type { Category, Grade, StudentInfo } from "@common/types"
	import type { ScheduleRow } from "./enrollment"

	interface Props {
		user: StudentInfo | null
		grade: Grade | null
		categories: Category[]
		schedule: ScheduleRow[]
	}

	const { user, grade, categories, schedule }: Props = $props()

	// Requirements name category ids; the labels come from the
	// categories list, which is the consumer's job to map.
	const categoryName = $derived(
		new Map(categories.map((c): [string, string] => [c.id, c.name])),
	)

	function requirementLabel(id: number): string {
		const requirement = grade?.requirements.find(
			(r): boolean => r.id === id,
		)
		if (requirement === undefined) {
			return ""
		}
		return requirement.category_ids
			.map((c): string => categoryName.get(c) ?? c)
			.join(" / ")
	}

	const allMet = $derived(
		user !== null &&
			user.requirements.every((r): boolean => r.met) &&
			user.distinct_categories_used >= user.min_distinct_categories,
	)
</script>

{#if user !== null}
	<section>
		<h2>Your account</h2>
		<dl class="grid">
			<dt>Name</dt>
			<dd>{user.name}</dd>
			<dt>Grade</dt>
			<dd>{grade?.name ?? user.grade_id}</dd>
			<dt>ID</dt>
			<dd>{user.id}</dd>
		</dl>
		<form method="post" action="/student/logout">
			<button>Sign out</button>
		</form>
	</section>
{/if}

{#if grade !== null && user !== null}
	<section>
		<h2>Status</h2>
		<!--
			Openness is the server's answer, derived from the window's
			two bounds. Nothing here recomputes it from the clock: the
			page and the write functions must agree, or a student is
			offered a button that cannot work.
		-->
		{#if grade.is_open}
			<p>
				Enrollment is <strong>open</strong> for your grade.
				{#if grade.closes_at !== null}
					It closes on {new Date(grade.closes_at).toLocaleString()}.
				{/if}
			</p>
		{:else}
			<p>
				Enrollment is <strong>closed</strong> for your grade. You may
				not make any changes.
				{#if grade.opens_at !== null && new Date(grade.opens_at) > new Date()}
					It opens on {new Date(grade.opens_at).toLocaleString()}.
				{/if}
			</p>
		{/if}
		<p>
			Your selections occupy
			<strong>{user.budgeted_periods_used}</strong>
			{user.budgeted_periods_used === 1
				? "period"
				: "periods"}{#if user.max_budgeted_periods !== null}, out of a
				maximum of
				<strong>{user.max_budgeted_periods}</strong>{/if}.
		</p>
		{#if user.min_distinct_categories > 0}
			<p>
				Your enrollments span
				<strong>{user.distinct_categories_used}</strong>
				{user.distinct_categories_used === 1
					? "category"
					: "categories"}; at least
				<strong>{user.min_distinct_categories}</strong>
				{user.min_distinct_categories === 1 ? "is" : "are"} required.
			</p>
		{/if}
		{#if user.requirements.length > 0 || user.min_distinct_categories > 0}
			{#if allMet}
				<p>You have satisfied your requirements.</p>
			{:else}
				<p>
					You have <strong>not</strong> satisfied your requirements.
				</p>
			{/if}
		{/if}
	</section>
{/if}

{#if user !== null && user.requirements.length > 0}
	<section>
		<h2>Requirements</h2>
		<div class="scrolls">
			<table>
				<thead>
					<tr>
						<th scope="col" rowspan="2">Categories</th>
						<th scope="colgroup" colspan="2">Periods</th>
						<th scope="col" rowspan="2">Status</th>
					</tr>
					<tr>
						<th scope="col">Enrolled</th>
						<th scope="col">Required</th>
					</tr>
				</thead>
				<tbody>
					{#each user.requirements as req (req.id)}
						<tr>
							<th scope="row">{requirementLabel(req.id)}</th>
							<td>{req.satisfied_periods}</td>
							<td>{req.min_period_count}</td>
							<td>{req.met ? "OK" : "Unsatisfied"}</td>
						</tr>
					{/each}
				</tbody>
			</table>
		</div>
	</section>
{/if}

<section>
	<h2>Your schedule</h2>
	<div class="scrolls">
		<table>
			<thead>
				<tr>
					<th scope="col">Period</th>
					<th scope="col">ID</th>
					<th scope="col">Title</th>
					<th scope="col">Location</th>
					<th scope="col">Categories</th>
				</tr>
			</thead>
			<tbody>
				{#each schedule as row (row.key)}
					{@const empty =
						row.courses.length === 0 ? "Empty" : undefined}
					<tr>
						<th scope="row">{row.label}</th>
						<td aria-label={empty}>
							{#each row.courses as course, position (course.id)}
								{#if position > 0},{" "}{/if}
								<code>{course.id}</code>
							{/each}
						</td>
						<td aria-label={empty}>
							{row.courses.map((c): string => c.name).join(", ")}
						</td>
						<td aria-label={empty}>
							{row.courses
								.map((c): string => c.location)
								.join(", ")}
						</td>
						<td aria-label={empty}>
							{row.courses
								.map((c): string => c.category_id)
								.join(", ")}
						</td>
					</tr>
				{:else}
					<tr>
						<td colspan="5">Nothing scheduled yet.</td>
					</tr>
				{/each}
			</tbody>
		</table>
	</div>
</section>
